config/routes.rb
Rails.application.routes.draw do
  resources :rss_feeds do
    collection do
      get "titles"
      get "all_latest_feeds"
      get "reader"
    end
  end
  
  get '/home', to: 'home#index'
  root 'home#index'
  
  get '/admin', to: 'rss_feeds#index', as: :admin
  
  match '/fhir_client/practitioner', to: 'fhir_client#practitioner', via: :post
  match '/fhir_client/patient', to: 'fhir_client#patient', via: :post
  get '/fhir_client/patient/:patient', to: 'fhir_client#patient', as: :fhir_patient
  get '/fhir_client/practitioner/:practitioner', to: 'fhir_client#practitioner', as: :fhir_practitioner

end

app/models/concerns/rss_fetch_parse.rb
module RssFetchParse
  extend ActiveSupport::Concern

  module ClassMethods
    def fetch_and_parse_feeds all_feeds
      urls = all_feeds.collect { |rss_feed| rss_feed.feed_url }.compact
      Feedjira::Feed.fetch_and_parse(urls)
    end

    def get_latest_feeds
      all_feeds = all
      entries = []
      parsed_feeds = fetch_and_parse_feeds(all_feeds)
      all_feeds.each do |feed|
        parsed_feeds[feed.feed_url].try(:entries).try(:each) do |entry|
          entries << entry
        end
      end
      entries.uniq.sort_by { |entry| entry.published }.reverse.first(100)
    end
  end
end

app/models/rss_feed.rb
class RssFeed < ActiveRecord::Base
  validates_presence_of :name, :feed_url
  validates_uniqueness_of :name
  validates_format_of :feed_url, :with => URI::regexp(%w(http https file))

  include RssFetchParse
end

app/models/rss_feed_result.rb
class RssFeedResult < ActiveRecord::Base
  
  def self.get_relevant_feeds(search_items)
    title_like_query_str = search_items.collect { |item| "title like \"%#{item}%\"" }.join(" OR ")
    description_like_query_str = search_items.collect { |item| "description like \"%#{item}%\"" }.join(" OR ")
    where("#{title_like_query_str} or #{description_like_query_str}").order("published_date desc")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fhir_client_controller.rb
class FhirClientController < ApplicationController
  
  def practitioner
    @patients = []
    practitioner_id = params["practitioner"]
    begin
      practitioner_fhir = RestClient.get('http://fhirtest.uhn.ca/baseDstu2/Practitioner/' + practitioner_id)
      encounters_fhir = RestClient.get('http://fhirtest.uhn.ca/baseDstu2/Encounter?practitioner=' + practitioner_id)
      
      encounters = Hash.from_xml(encounters_fhir)["Bundle"]["entry"]
      practitioner_hash = Hash.from_xml(practitioner_fhir)
      @practitioner_name = begin 
        practitioner_hash["Practitioner"]["name"]["text"]["value"] 
      rescue
        practitioner_hash["Practitioner"]["name"]["given"]["value"] + ", " + practitioner_hash["Practitioner"]["name"]["family"]["value"]
      end
      
      if !encounters.blank?
        encounters.each do |encounter|
          patient = {}
          patient_id = encounter["resource"]["Encounter"]["patient"]["reference"]["value"]
          patient_fhir = RestClient.get('http://fhirtest.uhn.ca/baseDstu2/' + patient_id)
          patient_name = Hash.from_xml(patient_fhir)["Patient"]["name"]["given"]["value"] + ", " + Hash.from_xml(patient_fhir)["Patient"]["name"]["family"]["value"]
          patient[:name] = patient_name
          patient[:patient_id] = patient_id.split("/").last
          @patients << patient
        end
        @patients.uniq!
      end
      
    rescue
      render action: 'not_found'
    end
  end
  
  def patient
    @conditions = []
    patient_id = params["patient"]
    begin
      patient_fhir = RestClient.get('http://fhirtest.uhn.ca/baseDstu2/Patient/' + patient_id)
      conditions_fhir = RestClient.get('http://fhirtest.uhn.ca/baseDstu2/Condition?patient=' + patient_id)
      @patient_given_name = Hash.from_xml(patient_fhir)["Patient"]["name"]["given"]["value"]
      @patient_family_name = Hash.from_xml(patient_fhir)["Patient"]["name"]["family"]["value"]
      puts Hash.from_xml(conditions_fhir)
      fetched_conditions = Hash.from_xml(conditions_fhir)["Bundle"]["entry"]
      if !fetched_conditions.blank?
        if fetched_conditions.kind_of?(Array)
          fetched_conditions.each do |condition|
            puts condition.inspect
            @conditions << condition["resource"]["Condition"]["code"]["text"]["value"]
          end
        else
          @conditions << fetched_conditions["resource"]["Condition"]["code"]["text"]["value"]
        end
        
        @conditions.uniq!
      end
    rescue
      render action: 'not_found'
    end
    
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    
  end
end

app/controllers/rss_feeds_controller.rb
class RssFeedsController < ApplicationController
  before_action :set_rss_feed, only: [:show, :edit, :update, :destroy]
  before_action :set_as_admin

  def index
    @rss_feeds = RssFeed.all
  end

  def show
  end

  def new
    @rss_feed = RssFeed.new
  end

  def edit
  end

  def create
    @rss_feed = RssFeed.new(rss_feed_params)

    if @rss_feed.save
      redirect_to @rss_feed, notice: 'Rss feed was successfully created.'
    else
      render :new
    end
  end

  def update
    if @rss_feed.update(rss_feed_params)
      redirect_to @rss_feed, notice: 'Rss feed was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @rss_feed.destroy
    redirect_to rss_feeds_url, notice: 'Rss feed was successfully destroyed.'
  end

  def titles
    @all_feeds = RssFeed.all
    @parsed_feeds = RssFeed.fetch_and_parse_feeds(@all_feeds)
  end

  def reader
    # will need this if we have filter.
    # currently not needed.
  end

  def all_latest_feeds
    @latest_feeds = RssFeed.get_latest_feeds
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_rss_feed
    @rss_feed = RssFeed.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def rss_feed_params
    params.require(:rss_feed).permit(:name, :feed_url, :description, :crawl)
  end
  
  def set_as_admin
    @admin = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fhir_client_helper.rb
module FhirClientHelper
  
  def highlight(text, words)
    words.each do |word|
      text = text.gsub(/#{word}/i, "<hlt>#{word}</hlt>")
    end
    text
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rss_feeds_helper.rb
module RssFeedsHelper
end

app/views/fhir_client/not_found.html.erb
<div class='back'>
    <%= link_to 'Back', root_path, :class => 'btn btn-primary' %>
</div>
<div class="page-header">
  <h2>404 Not Found</h2>
</div>

app/views/fhir_client/patient.html.erb
<div class='back'>
  <% if params["practitioner"].blank? %>
    <%= link_to 'Back', root_path, :class => 'btn btn-primary' %>
  <% else %>
    <%= link_to 'Back', fhir_practitioner_path(params["practitioner"]), :class => 'btn btn-primary' %>
  <% end %>
    
</div>
<h2>Conditions of Patient - <%= @patient_family_name %>, <%= @patient_given_name %></h2>
<% if @conditions.blank? %>
  NO CONDITIONS FOUND
<% else %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Conditions</th>
    </tr>
  </thead>
  <tbody>
    <% if !@conditions.blank? %>
      <% @conditions.each do |condition| %>
        <tr>
          <td><%= condition %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h2>Related RSS Information</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Published Date</th>
    </tr>
  </thead>
  <tbody>
    <% RssFeedResult.get_relevant_feeds(@conditions).each do |feed_data| %>
      <tr>
        <td><a href="<%= feed_data.link %>" target='_blank'><%= highlight(feed_data.title, @conditions).html_safe %></a></td>
        <td><a href="<%= feed_data.link %>" target='_blank'><%= highlight(feed_data.description, @conditions).html_safe  %></a></td>
        <td><%= feed_data.published_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/fhir_client/practitioner.html.erb
<div class='back'>
    <%= link_to 'Back', root_path, :class => 'btn btn-primary' %>
</div>
<div class="page-header">
  <h2>Hello, <%= @practitioner_name %></h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Patients</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to patient[:name], fhir_patient_path(patient[:patient_id]) + "?practitioner=" + params[:practitioner] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<div class='back'>
    <%= link_to 'Admin', admin_path, :class => 'btn btn-primary' %>
</div>
<div class="home">
  <form>
    I am a 
    <select class="target">
      <option value="Patient" selected="selected">Patient</option>
      <option value="Practitioner">Practitioner</option>
    </select>
  </form>
  <div class="hidden" id="practitioner">
     <%= form_tag(fhir_client_practitioner_path) do %>
     <p> 
      Enter your Practitioner ID
     </p> 
     <p>
      <input name="practitioner" type="text">
     </p>
     <p>
      <%= submit_tag 'Submit' %>
     </p>
     <% end %>
   </div>
  <div id="patient">
    <%= form_tag(fhir_client_patient_path) do %>
    <p>
      Enter your Patient ID
    </p>
    <p>
      <input name="patient" type="text">
    </p>
    <p>  
      <input type="submit" value="submit">
    </p>
    <% end %>
  </div>
</div>

app/views/layouts/_admin.html.erb
<div class="span9">
  <div class="span5">
    <h1>RSS Feed Reader</h1>
  </div>
  <div class="back">
    <%= link_to 'Read Feeds', reader_rss_feeds_path,
                :class => 'btn btn-primary' %>
    <%= link_to 'List Feeds', rss_feeds_path,
                :class => 'btn btn-primary' %>
    <%= link_to 'User Portal', root_path, :class => 'btn btn-primary' %>
  </div>
</div>

app/views/layouts/_home.html.erb
<div class="span9">
  <div class="span5">
    <h1>MedInfo Portal</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedReader</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>

<div class="container">
  <div class="row">
    <% if @admin %>
      <%= render partial: 'layouts/admin' %>
    <% else %>
      <%= render partial: 'layouts/home' %>
    <% end %>
    <div class="span11">
      <% flash.each do |name, msg| %>
        <div class="alert alert-success">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>
      <div class="span10">
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/rss_feeds/_form.html.erb
<%= simple_form_for @rss_feed, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.input :name %>
  <%= f.input :feed_url %>
  
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :crawl, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :crawl %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rss_feeds_path, :class => 'btn' %>
  </div>
<% end %>

app/views/rss_feeds/_latest_feed.html.erb
<div class="row feed_box">
  <p class="title">
    <%= feed.title %>
    <br>
    URL: <%= feed.url %>
  </p>
  <p>
    <b>Published On : </b> <%= feed.published %>
  </p>
  <p>
    <%=raw feed.summary %>
  </p>
</div>

app/views/rss_feeds/all_latest_feeds.js.erb
$('#reader').html("<%= escape_javascript(render :partial => 'latest_feed', :collection => @latest_feeds, :as => :feed) %>");

app/views/rss_feeds/edit.html.erb
<%- model_class = RssFeed -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/rss_feeds/index.html.erb
<%- model_class = RssFeed -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>
<table id="list_feeds" class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Feed URL</th>
      <th>Title</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rss_feeds.each do |rss_feed| %>
      <tr>
        <td><%= rss_feed.name %></td>
        <td><%= link_to rss_feed.feed_url, rss_feed_path(rss_feed) %></td>
        <td><span id="<%= Digest::MD5.hexdigest(rss_feed.feed_url) %>">Loading...</span></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rss_feed_path(rss_feed), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      rss_feed_path(rss_feed),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rss_feed_path,
            :class => 'btn btn-primary' %>

app/views/rss_feeds/new.html.erb
<%- model_class = RssFeed -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/rss_feeds/reader.html.erb
<div id="reader" data-no-turbolink>
  Loading........
</div>

app/views/rss_feeds/show.html.erb
<%- model_class = RssFeed -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @rss_feed.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:feed_url) %>:</strong></dt>
  <dd><%= @rss_feed.feed_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @rss_feed.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              rss_feeds_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rss_feed_path(@rss_feed), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              rss_feed_path(@rss_feed),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/rss_feeds/titles.js.erb
<% @all_feeds.each do |feed| %>
$('#<%= Digest::MD5.hexdigest feed.feed_url %>').replaceWith("<%= @parsed_feeds[feed.feed_url].title rescue "Failed to Load" %>");
<% end %>